import json
import re

tag_translations = {
    "ActivityLog": "活动日志",
    "ApiKey": "API密钥",
    "Artists": "艺术家",
    "Audio": "音频",
    "Backup": "备份",
    "Branding": "品牌",
    "Channels": "频道",
    "ClientLog": "客户端日志",
    "Collection": "收藏",
    "Configuration": "配置",
    "Dashboard": "控制台",
    "Devices": "设备",
    "DisplayPreferences": "显示偏好",
    "DynamicHls": "动态HLS",
    "Environment": "环境",
    "Filter": "过滤器",
    "Genres": "流派",
    "HlsSegment": "HLS分段",
    "Image": "图像",
    "InstantMix": "即时混音",
    "ItemLookup": "项目查找",
    "ItemRefresh": "项目刷新",
    "ItemUpdate": "项目更新",
    "Items": "项目",
    "Library": "媒体库",
    "LibraryStructure": "媒体库结构",
    "LiveTv": "实时电视",
    "Localization": "本地化",
    "Lyrics": "歌词",
    "MediaInfo": "媒体信息",
    "MediaSegments": "媒体分段",
    "Movies": "电影",
    "MusicGenres": "音乐流派",
    "Package": "包",
    "Persons": "人物",
    "Playlists": "播放列表",
    "Playstate": "播放状态",
    "Plugins": "插件",
    "QuickConnect": "快速连接",
    "RemoteImage": "远程图像",
    "ScheduledTasks": "计划任务",
    "Search": "搜索",
    "Session": "会话",
    "Startup": "启动",
    "Studios": "工作室",
    "Subtitle": "字幕",
    "Suggestions": "建议",
    "SyncPlay": "同步播放",
    "System": "系统",
    "TimeSync": "时间同步",
    "Tmdb": "TMDB",
    "Trailers": "预告片",
    "Trickplay": "快进快退",
    "TvShows": "电视节目",
    "UniversalAudio": "通用音频",
    "User": "用户",
    "UserLibrary": "用户媒体库",
    "UserViews": "用户视图",
    "VideoAttachments": "视频附件",
    "Videos": "视频",
    "Years": "年份",
}

word_translations = {
    # === subjects ===
    "activity log entries": "活动日志条目",
    "activity log entry": "活动日志条目",
    "activity log": "活动日志",
    "additional parts": "额外部分",
    "additional user": "额外用户",
    "album artists": "专辑艺术家",
    "all keys": "所有密钥",
    "all items": "所有项目",
    "all users": "所有用户",
    "all persons": "所有人物",
    "all parents": "所有父级",
    "all auth providers": "所有身份验证提供者",
    "all password reset providers": "所有密码重置提供者",
    "all syncplay groups": "所有同步播放组",
    "all currently present backups": "所有当前存在的备份",
    "alternate video sources": "备用视频源",
    "api key": "API密钥",
    "api keys": "API密钥",
    "application configuration": "应用程序配置",
    "application": "应用程序",
    "artist": "艺术家",
    "artists": "艺术家",
    "audio hls playlist stream": "音频HLS播放列表流",
    "audio stream": "音频流",
    "audio segment": "音频片段",
    "auth providers": "身份验证提供者",
    "auth token": "身份验证令牌",
    "authentication information": "身份验证信息",
    "available backups": "可用备份",
    "available channels": "可用频道",
    "available countries": "可用国家",
    "available drives": "可用驱动器",
    "available fallback font files": "可用后备字体文件",
    "available lineups": "可用频道列表",
    "available live tv channels": "可用实时电视频道",
    "available live tv epgs": "可用实时电视节目指南",
    "available live tv services": "可用实时电视服务",
    "available packages": "可用软件包",
    "available remote image providers": "可用远程图像提供者",
    "available remote images": "可用远程图像",
    "available server log files": "可用服务器日志文件",
    "backup archive manifest": "备份归档清单",
    "backup directory": "备份目录",
    "base64 encoded": "Base64编码",
    "bitrate": "比特率",
    "book remote search": "书籍远程搜索",
    "box set remote search": "合集远程搜索",
    "branding configuration": "品牌配置",
    "branding css": "品牌CSS",
    "capabilities": "能力",
    "channel features": "频道功能",
    "channel items": "频道项目",
    "channel mapping options": "频道映射选项",
    "channel mappings": "频道映射",
    "channel": "频道",
    "channels": "频道",
    "client": "客户端",
    "collection": "收藏",
    "collections": "收藏",
    "configuration pages": "配置页面",
    "configuration": "配置",
    "content type": "内容类型",
    "contents": "内容",
    "critic review": "评论评分",
    "cultures": "文化",
    "current utc time": "当前UTC时间",
    "current quick connect state": "当前快速连接状态",
    "custom splashscreen": "自定义启动画面",
    "dashboard configuration page": "控制台配置页面",
    "default directory browser": "默认目录浏览器",
    "default metadataoptions object": "默认MetadataOptions对象",
    "default values": "默认值",
    "default listings provider info": "默认列表提供者信息",
    "device": "设备",
    "devices": "设备",
    "directory": "目录",
    "display message": "显示消息",
    "display preferences": "显示偏好",
    "document": "文档",
    "encoding": "编码",
    "endpoint": "端点",
    "entries": "条目",
    "entry": "条目",
    "epgs": "电子节目指南",
    "epg": "电子节目指南",
    "episode": "剧集",
    "episodes": "剧集",
    "external lyric file": "外部歌词文件",
    "external subtitle file": "外部字幕文件",
    "external source": "外部源",
    "external id info": "外部ID信息",
    "fallback font file": "后备字体文件",
    "fallback font files": "后备字体文件",
    "favorite": "收藏",
    "file system": "文件系统",
    "filesystem": "文件系统",
    "first user": "第一个用户",
    "folder": "文件夹",
    "folders": "文件夹",
    "forgot password pin": "忘记密码PIN",
    "forgot password process": "忘记密码流程",
    "format": "格式",
    "genre": "流派",
    "genres": "流派",
    "grouping options": "分组选项",
    "guide info": "指南信息",
    "hls live stream": "HLS直播流",
    "hls video playlist": "HLS视频播放列表",
    "hls video playlist stream": "HLS视频播放列表流",
    "hls video segment": "HLS视频分段",
    "hls subtitle playlist": "HLS字幕播放列表",
    "image tiles playlist": "图像磁贴播放列表",
    "image": "图像",
    "images": "图像",
    "info": "信息",
    "information": "信息",
    "initial startup wizard configuration": "初始启动向导配置",
    "instant playlist": "即时播放列表",
    "item counts": "项目计数",
    "item image infos": "项目图像信息",
    "item image": "项目图像",
    "item": "项目",
    "items": "项目",
    "keys": "密钥",
    "key": "密钥",
    "known countries": "已知国家",
    "known cultures": "已知文化",
    "known parental ratings": "已知家长分级",
    "latest channel items": "最新频道项目",
    "latest media": "最新媒体",
    "legacy query filters": "遗留查询过滤器",
    "library options info": "媒体库选项信息",
    "library options": "媒体库选项",
    "library": "媒体库",
    "libraries": "媒体库",
    "library scan": "媒体库扫描",
    "listings provider": "列表提供者",
    "listing provider": "列表提供者",
    "live playback media info": "实时播放媒体信息",
    "live tv channel stream": "实时电视频道流",
    "live tv channel": "实时电视频道",
    "live tv channels": "实时电视频道",
    "live tv epgs": "实时电视节目指南",
    "live tv program": "实时电视节目",
    "live tv recording stream": "实时电视录制流",
    "live tv recording groups": "实时电视录制组",
    "live tv recording series": "实时电视录制系列",
    "live tv recording": "实时电视录制",
    "live tv recordings": "实时电视录制",
    "live tv series timer": "实时电视系列定时器",
    "live tv series timers": "实时电视系列定时器",
    "live tv timer": "实时电视定时器",
    "live tv timers": "实时电视定时器",
    "live tv": "实时电视",
    "local user": "本地用户",
    "local trailers": "本地预告片",
    "localization options": "本地化选项",
    "log file": "日志文件",
    "login screen": "登录屏幕",
    "lyrics": "歌词",
    "lyric": "歌词",
    "media folders": "媒体文件夹",
    "media path": "媒体路径",
    "media paths": "媒体路径",
    "media segments": "媒体分段",
    "media source": "媒体源",
    "member": "成员",
    "message": "消息",
    "metadata editor info": "元数据编辑器信息",
    "metadata": "元数据",
    "movie recommendations": "电影推荐",
    "movie remote search": "电影远程搜索",
    "movie": "电影",
    "movies": "电影",
    "music album remote search": "音乐专辑远程搜索",
    "music artist remote search": "音乐艺术家远程搜索",
    "music genre": "音乐流派",
    "music genres": "音乐流派",
    "music video remote search": "音乐视频远程搜索",
    "music": "音乐",
    "named configuration": "命名配置",
    "network paths": "网络路径",
    "network": "网络",
    "next up episodes": "下一集剧集",
    "options": "选项",
    "original file": "原始文件",
    "original items": "原始项目",
    "package repositories": "软件包仓库",
    "package repository": "软件包仓库",
    "package": "软件包",
    "packages": "软件包",
    "parent path": "父路径",
    "parental ratings": "家长分级",
    "parents": "父级",
    "password": "密码",
    "password reset providers": "密码重置提供者",
    "path": "路径",
    "paths": "路径",
    "person": "人物",
    "persons": "人物",
    "physical paths": "物理路径",
    "pin": "PIN码",
    "playback session": "播放会话",
    "playback progress": "播放进度",
    "playback": "播放",
    "playable media types": "可播放媒体类型",
    "playlist": "播放列表",
    "playlists": "播放列表",
    "plugin configuration": "插件配置",
    "plugin": "插件",
    "plugins": "插件",
    "public information": "公开信息",
    "publicly visible users": "公开可见用户",
    "query filters": "查询过滤器",
    "query": "查询",
    "quick connect request": "快速连接请求",
    "quick connect state": "快速连接状态",
    "quick connect": "快速连接",
    "rating": "评分",
    "ratings": "评分",
    "recording folders": "录制文件夹",
    "recording group": "录制组",
    "recording groups": "录制组",
    "recording series": "录制系列",
    "recording": "录制",
    "recordings": "录制",
    "remote access": "远程访问",
    "remote command": "远程命令",
    "remote commands": "远程命令",
    "remote image providers": "远程图像提供者",
    "remote images": "远程图像",
    "remote image": "远程图像",
    "remote lyrics": "远程歌词",
    "remote search": "远程搜索",
    "remote subtitles": "远程字幕",
    "remote subtitle": "远程字幕",
    "repositories": "仓库",
    "repository": "仓库",
    "request endpoint": "请求端点",
    "result": "结果",
    "results": "结果",
    "root folder": "根文件夹",
    "saved personal rating": "已保存的个人评分",
    "search criteria": "搜索条件",
    "search hint result": "搜索结果提示",
    "seasons": "季",
    "season": "季",
    "series remote search": "剧集远程搜索",
    "series timers": "系列定时器",
    "series timer": "系列定时器",
    "series": "剧集",
    "server log files": "服务器日志文件",
    "session": "会话",
    "sessions": "会话",
    "similar items": "类似项目",
    "song": "歌曲",
    "special features": "特殊功能",
    "specified task": "指定任务",
    "specified tasks": "指定任务",
    "specified format": "指定格式",
    "specified audio segment": "指定音频片段",
    "splashscreen": "启动画面",
    "startup wizard": "启动向导",
    "startup wizard configuration": "启动向导配置",
    "state": "状态",
    "status": "状态",
    "stream": "流",
    "studio": "工作室",
    "studios": "工作室",
    "subtitle": "字幕",
    "subtitles": "字幕",
    "suggestions": "建议",
    "syncplay group": "同步播放组",
    "syncplay groups": "同步播放组",
    "system command": "系统命令",
    "task triggers": "任务触发器",
    "task": "任务",
    "tasks": "任务",
    "the server": "服务器",
    "the item": "项目",
    "the user": "用户",
    "the backup": "备份",
    "the application": "应用程序",
    "the item's external id info": "项目的外部ID信息",
    "the item's image": "项目的图像",
    "the item's lyrics": "项目的歌词",
    "the item's content type": "项目的内容类型",
    "the joined syncplay group": "已加入的同步播放组",
    "the library": "媒体库",
    "the main media item": "主媒体项目",
    "the playlist": "播放列表",
    "the root folder": "根文件夹",
    "the server's file system": "服务器的文件系统",
    "the system": "系统",
    "the user's image": "用户的图像",
    "the entire library": "整个媒体库",
    "theme songs": "主题曲",
    "theme videos": "主题视频",
    "timers": "定时器",
    "timer": "定时器",
    "timing data": "计时数据",
    "tmdb image configuration options": "TMDB图像配置选项",
    "trailer remote search": "预告片远程搜索",
    "trailer": "预告片",
    "trailers": "预告片",
    "trickplay tile image": "快进快退磁贴图像",
    "trickplay": "快进快退",
    "tuner host types": "调谐器主机类型",
    "tuner host": "调谐器主机",
    "tuner hosts": "调谐器主机",
    "tuner": "调谐器",
    "tuners": "调谐器",
    "tv season": "电视季",
    "tv series": "电视剧集",
    "tv tuner": "电视调谐器",
    "upcoming episodes": "即将播出的剧集",
    "user by id": "用户",
    "user configuration": "用户配置",
    "user data": "用户数据",
    "user image": "用户图像",
    "user library": "用户媒体库",
    "user media folders": "用户媒体文件夹",
    "user policy": "用户策略",
    "user profile image": "用户头像",
    "user view grouping options": "用户视图分组选项",
    "user views": "用户视图",
    "user's library": "用户的媒体库",
    "user's password": "用户的密码",
    "user's saved personal rating": "用户已保存的个人评分",
    "user's rating": "用户的评分",
    "user": "用户",
    "users": "用户",
    "video attachment": "视频附件",
    "video attachments": "视频附件",
    "video hls playlist stream": "视频HLS播放列表流",
    "video sources": "视频源",
    "video stream": "视频流",
    "virtual folder": "虚拟文件夹",
    "virtual folders": "虚拟文件夹",
    "year": "年份",
    "years": "年份",

    # === verbs (base) ===
    "adds": "添加",
    "add": "添加",
    "applies": "应用",
    "apply": "应用",
    "authenticates": "验证",
    "authenticate": "验证",
    "authorizes": "授权",
    "authorize": "授权",
    "attempts to retrieve": "尝试检索",
    "cancel": "取消",
    "cancels": "取消",
    "close": "关闭",
    "closes": "关闭",
    "complete": "完成",
    "completes": "完成",
    "create": "创建",
    "creates": "创建",
    "delete": "删除",
    "deletes": "删除",
    "disable": "禁用",
    "disables": "禁用",
    "discover": "发现",
    "discovers": "发现",
    "download": "下载",
    "downloads": "下载",
    "enable": "启用",
    "enables": "启用",
    "find": "查找",
    "finds": "查找",
    "generate": "生成",
    "generates": "生成",
    "get": "获取",
    "gets": "获取",
    "initiate": "发起",
    "initiates": "发起",
    "install": "安装",
    "installs": "安装",
    "instruct": "指示",
    "instructs": "指示",
    "issue": "发出",
    "issues": "发出",
    "join": "加入",
    "joins": "加入",
    "leave": "离开",
    "mark": "标记",
    "marks": "标记",
    "merge": "合并",
    "merges": "合并",
    "modify": "修改",
    "modifies": "修改",
    "move": "移动",
    "moves": "移动",
    "notify": "通知",
    "notifies": "通知",
    "open": "打开",
    "opens": "打开",
    "ping": "心跳",
    "pings": "心跳",
    "redeem": "兑换",
    "redeems": "兑换",
    "refresh": "刷新",
    "refreshes": "刷新",
    "remove": "移除",
    "removes": "移除",
    "rename": "重命名",
    "renames": "重命名",
    "report": "报告",
    "reports": "报告",
    "request": "请求",
    "requests": "请求",
    "reset": "重置",
    "resets": "重置",
    "restart": "重启",
    "restarts": "重启",
    "restore": "恢复",
    "restores": "恢复",
    "search": "搜索",
    "searches": "搜索",
    "set": "设置",
    "sets": "设置",
    "shut": "关闭",
    "shuts": "关闭",
    "start": "启动",
    "starts": "启动",
    "stop": "停止",
    "stops": "停止",
    "test": "测试",
    "tests": "测试",
    "uninstall": "卸载",
    "uninstalls": "卸载",
    "unmark": "取消标记",
    "unmarks": "取消标记",
    "update": "更新",
    "updates": "更新",
    "upload": "上传",
    "uploads": "上传",
    "validate": "验证",
    "validates": "验证",

    # === prepositions & conjunctions ===
    " and ": " 和 ",
    " or ": " 或 ",
    " from ": " 从 ",
    " into ": " 到 ",
    " within ": " 在 ",
    " during ": " 期间 ",
    " about ": " 关于 ",
    " using ": " 使用 ",
    " based on ": " 基于 ",
    " according to": " 根据",

    # === other common ===
    "a ": "",
    "an ": "",
    "the ": "",
    "all ": "所有 ",
    "additional ": "额外 ",
    "alternate ": "备用 ",
    "audio": "音频",
    "available ": "可用 ",
    "by ": "按 ",
    "comma delimited": "逗号分隔",
    "currently ": "当前 ",
    "custom ": "自定义 ",
    "default ": "默认 ",
    "existing ": "现有 ",
    "external ": "外部 ",
    "failed": "失败",
    "first ": "第一个 ",
    "for ": "为 ",
    "general ": "通用 ",
    "given ": "指定 ",
    "has ": "已",
    "have ": "已",
    "http live streaming": "HTTP实时流媒体",
    "http": "HTTP",
    "in ": "在 ",
    "initial ": "初始 ",
    "installed ": "已安装 ",
    "is ": "是 ",
    "latest ": "最新 ",
    "legacy ": "遗留 ",
    "local ": "本地 ",
    "named ": "命名 ",
    "new ": "新 ",
    "next ": "下一个 ",
    "of ": "",
    "pending ": "待处理 ",
    "physical ": "物理 ",
    "pipe delimited": "管道符分隔",
    "present ": "存在 ",
    "public ": "公开 ",
    "publicly ": "公开 ",
    "recommended ": "推荐 ",
    "remote ": "远程 ",
    "single ": "单个 ",
    "special ": "特殊 ",
    "specified ": "指定 ",
    "successful": "成功",
    "to ": "到 ",
    "upcoming ": "即将 ",
    "using ": "使用 ",
    "virtual ": "虚拟 ",
    "visible ": "可见 ",
    "with ": "使用 ",
    "been ": "被 ",

    # === verbs with -ing / -ed forms ===
    "restarting": "重启中",
    "applying": "应用",
    "stopped": "已停止",
    "streaming": "流式传输",
    "playing": "正在播放",
    "buffering": "缓冲",
    "pairing": "配对",
    "encoding": "编码",
    "scrolled": "滚动",

    # === misc ===
    "api": "API",
    "assembly": "程序集",
    "before": "之前",
    "body": "请求体",
    "change": "更改",
    "command": "命令",
    "css": "CSS",
    "descriptor": "描述符",
    "down": "关闭",
    "downmix": "混音",
    "drives": "驱动器",
    "editor": "编辑器",
    "expected": "预期",
    "full": "完整",
    "ignore": "忽略",
    "name": "名称",
    "pin": "PIN码",
    "play": "播放",
    "plays": "播放",
    "present": "存在",
    "size": "大小",
    "encoded as": "编码为",
    "existing archive": "现有归档",
    "file": "文件",
    "files": "文件",
    "forgot ": "忘记 ",
    "full seconds": "整秒",
    "guid": "GUID",
    "header parameter": "头部参数",
    "hosts": "主机",
    "initialdelay": "初始延迟",
    "interval": "间隔",
    "into": "到",
    "intros": "开场",
    "json body": "JSON体",
    "lineup": "频道列表",
    "lineups": "频道列表",
    "listings": "节目表",
    "manifest": "清单",
    "mapping options": "映射选项",
    "mappings": "映射",
    "metadataoptions": "MetadataOptions",
    "ms": "毫秒",
    "object": "对象",
    "page": "页面",
    "pages": "页面",
    "path": "路径",
    "paths": "路径",
    "pin": "PIN码",
    "program": "节目",
    "progress": "进度",
    "providers": "提供者",
    "provider": "提供者",
    "retry the operation": "重试操作",
    "screen": "屏幕",
    "source": "源",
    "sources": "源",
    "state": "状态",
    "streaming": "流式传输",
    "surround sound": "环绕声",
    "the": "",
    "tile": "磁贴",
    "tiles": "磁贴",
    "timer": "定时器",
    "timers": "定时器",
    "token": "令牌",
    "triggers": "触发器",
    "trigger": "触发器",
    "type": "类型",
    "types": "类型",
    "upnp": "UPnP",
    "utc": "UTC",
    "value": "值",
    "values": "值",
    "view": "视图",
    "views": "视图",
    "wizard": "向导",
    "active": "活动",
    "added": "已添加",
    "begun": "已开始",
    "browse": "浏览",
    "buffering": "缓冲",
    "content": "内容",
    "counts": "计数",
    "country": "国家",
    "countries": "国家",
    "critic": "评论",
    "culture": "文化",
    "cultures": "文化",
    "directory browser": "目录浏览器",
    "display": "显示",
    "drives": "驱动器",
    "drive": "驱动器",
    "encoding": "编码",
    "enabled": "已启用",
    "disabled": "已禁用",
    "ended": "已结束",
    "endpoint": "端点",
    "entire": "整个",
    "entry": "条目",
    "entries": "条目",
    "event": "事件",
    "feature": "功能",
    "features": "功能",
    "favorite": "收藏",
    "favorites": "收藏",
    "filter": "过滤器",
    "filters": "过滤器",
    "font": "字体",
    "format": "格式",
    "group": "组",
    "groups": "组",
    "grouping": "分组",
    "hint": "提示",
    "host": "主机",
    "image": "图像",
    "images": "图像",
    "index": "索引",
    "infos": "信息",
    "installation": "安装",
    "itemid": "项目ID",
    "key": "密钥",
    "keys": "密钥",
    "known": "已知",
    "list": "列表",
    "lists": "列表",
    "localization": "本地化",
    "login": "登录",
    "mapping": "映射",
    "member": "成员",
    "members": "成员",
    "mode": "模式",
    "model": "模型",
    "music": "音乐",
    "named": "命名",
    "network": "网络",
    "next": "下一个",
    "parent": "父级",
    "parents": "父级",
    "part": "部分",
    "parts": "部分",
    "password": "密码",
    "pause": "暂停",
    "personal": "个人",
    "ping": "心跳",
    "played": "已播放",
    "playing": "正在播放",
    "playstate": "播放状态",
    "preferences": "偏好",
    "previous": "上一个",
    "profile": "头像",
    "progress": "进度",
    "public": "公开",
    "query": "查询",
    "queue": "队列",
    "quick": "快速",
    "rating": "评分",
    "ratings": "评分",
    "ready": "就绪",
    "recommendations": "推荐",
    "recommended": "推荐",
    "record": "记录",
    "repositories": "仓库",
    "repository": "仓库",
    "reset": "重置",
    "restarting": "重启",
    "review": "评论",
    "root": "根",
    "scan": "扫描",
    "score": "评分",
    "season": "季",
    "seasons": "季",
    "seek": "跳转",
    "shuffle": "随机播放",
    "repeat": "重复",
    "single": "单个",
    "song": "歌曲",
    "sorting order": "排序顺序",
    "spatial audio": "空间音频",
    "specified": "指定",
    "splashscreen": "启动画面",
    "startup": "启动",
    "stereo": "立体声",
    "stream": "流",
    "streaming": "流式传输",
    "subs": "字幕",
    "suggestions": "建议",
    "system": "系统",
    "theme": "主题",
    "unplayed": "未播放",
    "upcoming": "即将",
    "version": "版本",
    "video range": "视频范围",
    "video ranges": "视频范围",
    "video": "视频",
    "view": "视图",
    "viewing": "正在查看",
    "views": "视图",
    "visible": "可见",
    "wait": "等待",
    "weekdays": "工作日",
    "weekends": "周末",
    "week": "周",
    "wizard": "向导",
    "year": "年份",
    "years": "年份",
    "album": "专辑",
    "albums": "专辑",
    "artist": "艺术家",
    "artists": "艺术家",
    "auth": "身份验证",
    "backdrop": "背景",
    "backup": "备份",
    "backups": "备份",
    "banner": "横幅",
    "book": "书籍",
    "box set": "合集",
    "branding": "品牌",
    "configuration": "配置",
    "dashboard": "控制台",
    "data": "数据",
    "disc": "光盘",
    "dynamic": "动态",
    "encoded": "编码",
    "environment": "环境",
    "episode": "剧集",
    "episodes": "剧集",
    "font": "字体",
    "formats": "格式",
    "front": "前端",
    "genres": "流派",
    "genre": "流派",
    "hls": "HLS",
    "instant": "即时",
    "internal": "内部",
    "library": "媒体库",
    "libraries": "媒体库",
    "live": "实时",
    "local": "本地",
    "logo": "徽标",
    "lyric": "歌词",
    "lyrics": "歌词",
    "media": "媒体",
    "metadata": "元数据",
    "movie": "电影",
    "movies": "电影",
    "music": "音乐",
    "options": "选项",
    "package": "包",
    "packages": "包",
    "person": "人物",
    "persons": "人物",
    "photo": "照片",
    "playback": "播放",
    "playlist": "播放列表",
    "playlists": "播放列表",
    "plugin": "插件",
    "plugins": "插件",
    "primary": "主要",
    "quick": "快速",
    "recordings": "录制",
    "recording": "录制",
    "remote": "远程",
    "result": "结果",
    "results": "结果",
    "screenshot": "截图",
    "search": "搜索",
    "series": "剧集",
    "server": "服务器",
    "session": "会话",
    "sessions": "会话",
    "similar": "类似",
    "source": "源",
    "startup": "启动",
    "status": "状态",
    "studio": "工作室",
    "studios": "工作室",
    "subtitle": "字幕",
    "subtitles": "字幕",
    "suggestion": "建议",
    "suggestions": "建议",
    "sync": "同步",
    "system": "系统",
    "themes": "主题",
    "theme": "主题",
    "thumb": "缩略图",
    "trailers": "预告片",
    "trailer": "预告片",
    "tv": "电视",
    "type": "类型",
    "types": "类型",
    "user": "用户",
    "users": "用户",
    "video": "视频",
    "videos": "视频",
    "view": "视图",
    "views": "视图",
    "virtual": "虚拟",
    "wizard": "向导",
    "year": "年份",
    "years": "年份",
}

def translate_summary(text):
    if not text:
        return text

    t = text.strip()

    # Handle "Marks/Unmarks X as Y" pattern
    t = re.sub(r'^Marks an item as (unplayed|played|a favorite) for user\.?$',
               lambda m: {'played': '将项目标记为已播放', 'unplayed': '将项目标记为未播放', 'a favorite': '将项目标记为收藏'}[m.group(1)], t)
    t = re.sub(r'^Marks an item as (unplayed|played|a favorite)\.?$',
               lambda m: {'played': '将项目标记为已播放', 'unplayed': '将项目标记为未播放', 'a favorite': '将项目标记为收藏'}[m.group(1)], t)
    t = re.sub(r'^Marks (.+) as (.+)\.?$', r'将\1标记为\2', t)
    t = re.sub(r'^Unmarks item as a favorite\.?$', '取消项目收藏标记', t)

    # Handle "Notifies/Notify X that Y" pattern
    t = re.sub(r'^Notify (.+) that (.+)\.?$', r'通知\1：\2', t)

    # Handle "Instructs/Instruct X (to) Y" pattern
    t = re.sub(r'^Instructs? (.+) to (.+)\.?$', r'指示\1：\2', t)

    # Handle "Issues/Issue X to Y" pattern
    t = re.sub(r'^Issues? (.+) to (.+)\.?$', r'向\2发出\1', t)

    # Handle "Reports/Report X" with "that" clause
    t = re.sub(r'^Reports? that (.+)\.?$', r'报告：\1', t)

    # Handle "Request X in Y" for SyncPlay
    t = re.sub(r'^Request (next|previous|pause|stop|unpause|seek) in (.+)\.?$', r'在\2中请求\1', t)
    t = re.sub(r'^Request (to .+) in (.+)\.?$', r'在\2中请求\1', t)

    # Handle "Apply/Applies X to Y"
    t = re.sub(r'^Applies? (.+) to (.+)\.?$', r'将\1应用到\2', t)

    # Handle "Generates or gets X"
    t = re.sub(r'^Generates or gets (.+)\.?$', r'生成或获取\1', t)

    # Handle "Notify/Notifies … that …"
    t = re.sub(r'^Notifies? (.+) that (.+)\.?$', r'通知\1：\2', t)

    # Handle "Set option" -> "设置选项"
    t = re.sub(r'^Sets? (.+) and (.+)\.?$', r'设置\1和\2', t)

    # Handle "Finds/Find X similar to Y"
    t = re.sub(r'^Finds? (.+) similar to (.+)\.?$', r'查找与\2类似的\1', t)

    # Handle "Close/Closes X" -> "关闭X"
    t = re.sub(r'^Close an? (.+)\.?$', r'关闭\1', t)

    # Apply word replacements (longest match first)
    sorted_words = sorted(word_translations.items(), key=lambda x: len(x[0]), reverse=True)
    for eng, chi in sorted_words:
        pattern = re.compile(re.escape(eng), re.IGNORECASE)
        t = pattern.sub(chi, t)

    # Clean up spaces
    t = t.replace("  ", " ").strip()
    t = re.sub(r'\s+', ' ', t)

    # Remove spurious spaces before punctuation
    t = re.sub(r'\s+([。,，])', r'\1', t)

    # Remove "of " artifacts (from empty replacement)
    t = re.sub(r'^\s*of\s+', '', t)
    t = re.sub(r'\s+of\s+', '', t)
    t = re.sub(r'\s+of$', '', t)

    # Fix "a", "an", "the" leftovers
    t = re.sub(r'\bthe\b', '', t)
    t = re.sub(r'\ba\b', '', t)
    t = re.sub(r'\ban\b', '', t)

    # Clean up multiple spaces again
    t = re.sub(r'\s+', ' ', t).strip()

    # Remove trailing/leading "的" if it's an artifact
    if t.startswith("的") or t.endswith("的"):
        t = t.strip("的").strip()

    # Ensure proper ending punctuation - just one period
    t = t.rstrip("。.")  # remove existing
    if t:
        t += "。"

    return t


def process_json(data):
    if isinstance(data, dict):
        new_data = {}
        for k, v in data.items():
            if k == "tags" and isinstance(v, list):
                new_data[k] = [tag_translations.get(tag, tag) for tag in v]
            elif k == "summary" and isinstance(v, str):
                new_data[k] = translate_summary(v)
            else:
                new_data[k] = process_json(v)
        return new_data
    elif isinstance(data, list):
        return [process_json(item) for item in data]
    else:
        return data


file_path = r'd:\Users\Documents\1\emby2openlist\jellyfin-openapi-stable.json'
output_path = r'd:\Users\Documents\1\emby2openlist\jellyfin-openapi-stable-zh.json'

with open(file_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

translated_data = process_json(data)

with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(translated_data, f, ensure_ascii=False, indent=2)

print(f"Translation completed. Saved to {output_path}")
